export const WS_CONNECT_REQUEST = "WS_CONNECT_REQUEST";
export const WS_CONNECT_SUCCESS = "WS_CONNECT_SUCCESS";
export const WS_CONNECT_FAILED = "WS_CONNECT_FAILED";
export const WS_DISCONNECTED = "WS_DISCONNECTED";